"""Update2

Revision ID: 2a9b0f3451d2
Revises: 00c4e934826e
Create Date: 2023-09-21 17:13:00.864822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9b0f3451d2'
down_revision = '00c4e934826e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('app_deadline',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('personal_deadline',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('personal_deadline',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('app_deadline',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
